###############
# SSHD CONFIG #
###############
- name: Ensure permissions on /etc/ssh/sshd_config are configured
  file:
    state: file
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600

- name: Allow SSH access only for users in ssh-user group
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^AllowGroups"
    line: "AllowGroups ssh-user"
  notify: restart ssh

- name: Ensure SSH X11 forwarding is disabled
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^X11Forwarding"
    line: "X11Forwarding no"

- name: Ensure SSH MaxAuthTries is set to 4 or less
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^(#)?MaxAuthTries \d'
    line: "MaxAuthTries 3"

# Setting this parameter forces users to enter a password when authenticating with ssh
- name: Ensure SSH IgnoreRhosts is enabled
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?IgnoreRhosts"
    line: "IgnoreRhosts yes"

- name: Ensure SSH HostbasedAuthentication is disabled
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?HostbasedAuthentication"
    line: "HostbasedAuthentication no"

- name: Disallow root SSH access
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"

- name: Ensure SSH PermitEmptyPasswords is disabled
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"

# Permitting users the ability to set environment variables through the SSH daemon could
# potentially allow users to bypass security controls (e.g. setting an execution path that has
# ssh executing trojan'd programs)
- name: Ensure SSH PermitUserEnvironment is disabled
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?PermitUserEnvironment"
    line: "PermitUserEnvironment no"

- name: Ensure only strong Ciphers are used
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^Ciphers"
    line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"

- name: Ensure only strong MAC algorithms are used
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^MACs"
    line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"

- name: Ensure only strong Key Exchange algorithms are used
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^KexAlgorithms"
    line: "KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"

- name: Ensure SSH Idle Timeout Interval is configured
  block:
    - name: Ensure SSH Idle Timeout Interval is configured - clientalive
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^(#)?ClientAliveInterval"
        line: "ClientAliveInterval 300"
    - name: Ensure SSH Idle Timeout Interval is configured - MaxAlive
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^(#)?ClientAliveCountMax"
        line: "ClientAliveCountMax 3"

- name: Ensure SSH LoginGraceTime is set to one minute or less
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?LoginGraceTime"
    line: "LoginGraceTime 60"

- name: Ensure SSH PAM is enabled
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^UsePAM"
    line: "UsePAM yes"

- name: Ensure SSH AllowTcpForwarding is disabled
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?AllowTcpForwarding"
    line: "AllowTcpForwarding no"

- name: Ensure SSH MaxStartups is configured
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?MaxStartups"
    line: "MaxStartups 10:30:100"

- name: Ensure SSH MaxSessions is limited
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?MaxSessions"
    line: "MaxSessions 10"
